### ISSUE TITLE
PondTemplate

### ISSUE THREAD

**Issue by CanadianHarp85** [Xytabich/FieldsOfSalt#1]
Only feverstonewilds_1.5.0-rc.2 and gourmand_1.2.6 were added to the server. This happens each attempt to join the server.

Running on 64 bit Windows 10.0.19045.0 with 96005 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
12/5/2024 9:49:09 PM: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, danatweaks@2.3.0, gourmand@1.2.6, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.Exception: Don't know how to instantiate item of class 'fieldsofsalt:pondtemplate' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 332
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 195
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 575
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 404
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 346
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/5/2024 3:32:31 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3900
Faulting application start time: 0x01db474c59eaf31f
Faulting application path: C:\Users\NH\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\NH\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 9c91c476-16d9-4873-8df6-fc94f735f948
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/5/2024 3:00:27 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x9eb0
Faulting application start time: 0x01db473b275fae53
Faulting application path: C:\Users\NH\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\NH\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7206d7a8-508c-4d33-89fe-74f91768fab8
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/5/2024 1:16:56 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x9c70
Faulting application start time: 0x01db47389cce281b
Faulting application path: C:\Users\NH\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\NH\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 69aed1e3-646a-476d-9571-d7d1f9678bc5
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Xytabich** [comment]
It looks like you're using some weird mix of old and new mods that is incompatible with the new version of the game.
